# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(default='desconocida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.FileField(default='algo.jpg', upload_to='commerce/media'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(default='desconocida'),
        ),
    ]
